src/components/common/DateCell.jsx
src/hooks/useSoftware/softwareFields.js
src/hooks/useSoftware/useSoftware.js

fixes IOD-100

---

.github/helpers/application-health.sh
.github/helpers/deploy-app.sh
.github/workflows/dev-app-build-deploy.yaml

IOD-119 Create Git Action for docker image build, deploy to DEV

---

.github/workflows/dev-app-build-deploy.yaml
.github/workflows/test-app-deploy.yaml

IOD-120 Create Git ACtion for TEST deploy

---

openshift/templates/citz-imb-slam-app/dc.yaml

Updating Image Location in Deployment Config

---

package.json
src/components/formik/FormikContainer.jsx

bug fix - entering new software no licensees condition

---

.github/workflows/dev-app-build-deploy.yaml

updated concurrency

---

.github/workflows/test-app-deploy.yaml

IOD-116 Typo

---

.github/workflows/prod-app-deploy.yaml

IOD-121 Create Action for PROD Deploy

---

src/pages/api/auth/[...nextauth].js

added console.log to troubleshoot

---

src/pages/api/auth/[...nextauth].js

remove console.log

---

openshift/templates/citz-imb-slam-app/service.yaml

Creating Openshift Service Template

---

src/hooks/useLicensees/useLicensees.js

fix variable name collision

---

src/pages/index.jsx

- Small addition to redirect from Home to Software. 
Tested on local dev environment and local containers.

IOD-206 Set temporary redirect to /software page.

---

src/hooks/useAPI/fetchAPI.js

changed the fetch url

---

src/hooks/useAPI/fetchAPI.js

change env variables

---

src/hooks/useAPI/fetchAPI.js
src/hooks/useAuth/useAuth.js

changed login url

---

src/hooks/useAPI/fetchAPI.js
src/hooks/useAuth/useAuth.js

changed default port

---

src/hooks/common/Fields.class.js
src/hooks/useAPI/fetchAPI.js
src/hooks/useAPI/useAPI.js
src/hooks/useSoftware/softwareFields.js

fixed save fail when no renewal date

---

src/components/formik/FormikContainer.jsx
src/components/formik/inputs/DropdownFormikControl.jsx

corrected linting errors

---

.github/workflows/dev-app-build-deploy.yaml
.github/workflows/test-app-deploy.yaml

change triggers

---

.eslintrc.json
.prettierrc
src/components/formik/FormikContainer.jsx
src/components/formik/inputs/SelectChipFormikControl.jsx
src/components/index.js
src/hooks/common/Fields.class.js
src/hooks/common/getFormFields.js
src/hooks/common/getTableColumns.js
src/hooks/common/transformOnFetch.js
src/hooks/common/transformOnSave.js
src/hooks/useForm/setInitialValues.js
src/hooks/useLicensees/licenseeFields.js
src/hooks/useLicensees/useLicensees.js

Real iod 220

---

src/components/navigation/Navigation.jsx

- Combined the License Management Icon and Text into one link

IOD-232 Combine License Management Icon and Text into one link

---

src/components/common/ModifiedCell.jsx
src/components/common/ModifiedDateCell.jsx
src/hooks/useLicensees/licenseeFields.js

- Added precision to the Date Modified display

IOD-233 Enhance Date Modified description for Software Licenses

---

src/components/formik/inputs/LicenseDropdownControl.jsx
src/components/formik/inputs/SelectChipFormikControl.jsx
src/hooks/useLicensees/licenseeFields.js

- Assigned Licenses select now shows quantity available. 
Tested on local build.

IOD-199 Added counts to licenses select.

---

src/components/common/QuantityAssigned.jsx
src/components/formik/inputs/LicenseDropdownControl.jsx
src/components/navigation/Navigation.jsx

- change the license management button to not light up when hovered
- fix the blue ring appearing when there are 0/0 licenses
- changed the warning colour of overused software in the licensee fields
- enhanced description of software in the licensee fields

frontend fixes 

---

src/components/navigation/UserMenu.jsx
src/hooks/useAuth/useAuth.js

- Removes unwanted console.log
- Skips provider choice page from next-auth.
Tested locally.

IOD- 251 Remove console log and skip nextauth prompt

---

src/components/formik/inputs/UserListControl.jsx

user list fix update

---

src/components/formik/inputs/UserItemControl.jsx
src/components/navigation/UserMenu.jsx

user id fixes and email fixes

---

openshift/templates/citz-imb-slam-app/dc.yaml

Adding Environment Variables to Deployment Config

---

openshift/templates/citz-imb-slam-app/dc.yaml

Indentation Error

---

.github/workflows/pull-request-auto-assign.yaml

Auto Assign Team Members to Pull Request

---

src/components/buttons/SaveCancelButtons.jsx
src/components/formik/FormikContainer.jsx

Changed Cancel button behaviour:
- If in edit mode, Cancel button returns form to non-edit state
- If in non-edit mode, Cancel button replaced with back button, which returns user to licensees or software

IOD-258 Cancel button behaviour

---

src/components/buttons/SaveCancelButtons.jsx
src/components/formik/FormikContainer.jsx

- Added check for /add page
Tested on local build

IOD-262 Cancel button fix

---

src/components/formik/FormikContainer.jsx
src/pages/software/add.jsx

BUG: Delete button appears even when adding new software/licensees

---

src/components/navigation/UserMenu.jsx

- Logout now removes Keycloak session as well.
Tested on local build, logging in and out many times.

IOD-252 Keycloak logout

---

src/hooks/useAPI/useAPI.js

- Add change to lowercase when updating or creating data involving emails
Tested on local build.

IOD-267 Force email to lowercase during update/create

---

src/components/formik/FormikContainer.jsx
src/components/formik/inputs/InputFormikControl.jsx
src/hooks/useLicensees/licenseeFields.js

error message appears when duplicate email is entered

---

src/components/formik/FormikContainer.jsx
src/hooks/useSoftware/softwareFields.js

Quantity gives error message if it is below zero
